spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/uniyeisi
spring.datasource.username=root
spring.datasource.password=Uniyeisi2026*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.secret=UniyeisiSeguridad2026ClaveSecreta32Caracteres